language: python
sudo: required

services:
  - docker

before_install:
  - docker build -t django_docker -f Dockerfile .

script:
  - docker run django_docker python manage.py test

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: $SECRETACCESSKEY
  region: "us-east-2"  
  app: "docker"
  env: "Docker-env "
  bucket_name: "elasticbeanstalk-us-east-2-216272097231"
  on:
    branch: master